version: "3"

services:
  signaling:
    tty: true
    build: gstreamer
    entrypoint:
      - cargo
      - run
      - --bin
      - gst-webrtc-signalling-server
    environment:
      - GST_DEBUG=3
    ports:
      - 8443:8443
